// for forums state
export const ACTION_GET_ALL_ANNOUNCEMENTS = 'announcements/GET_ALL_ANNOUNCEMENTS'
export const ACTION_GET_ANNOUNCEMENTS_COUNT = 'announcements/GET_ANNOUNCEMENTS_COUNT'
export const ACTION_GET_FILTERED_ANNOUNCEMENTS = 'announcements/GET_FILTERED_ANNOUNCEMENTS'
export const ACTION_BOOKMARK_ANNOUNCEMENT = 'announcements/BOOKMARK_ANNOUNCEMENT'
export const ACTION_UNBOOKMARK_ANNOUNCEMENT = 'announcements/UNBOOKMARK_ANNOUNCEMENT'

export const MUTATION_SET_ERROR = 'announcements/MUTATION_SET_ERROR'
export const MUTATION_SET_ALL_ANNOUNCEMENTS = 'announcements/MUTATION_SET_ALL_ANNOUNCEMENTS'
export const MUTATION_SET_ANNOUNCEMENT_COUNT = 'announcements/MUTATION_SET_ANNOUNCEMENT_COUNT'

export const GETTER_ALL_ANNOUNCEMENTS = 'announcements/GETTER_ALL_ANNOUNCEMENTS'
