// for forums state
export const ACTION_GET_ALL_ANNOUNCEMENTS = 'announcements/GET_ALL_ANNOUNCEMENTS'
export const ACTION_GET_ANNOUNCEMENTS_COUNT = 'announcements/GET_ANNOUNCEMENTS_COUNT'

export const MUTATION_SET_ERROR = 'announcements/MUTATION_SET_ERROR'
export const MUTATION_SET_ALL_ANNOUNCEMENTS = 'announcements/MUTATION_SET_ALL_ANNOUNCEMENTS'
export const MUTATION_SET_ANNOUNCEMENT_COUNT = 'announcements/MUTATION_SET_ANNOUNCEMENT_COUNT'

export const GETTER_ALL_ANNOUNCEMENTS = 'announcements/GETTER_ALL_ANNOUNCEMENTS'
